gibloc/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import *
from django.contrib.auth.views import login
import django
import squid.views
import squidguard.views
import tasker.views
import licenses.views
import certs.views
import mail.views
import hashez.views

admin.autodiscover()

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', 'gibloc.views.home', name='home'),
    # url(r'^gibloc/', include('gibloc.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$',TemplateView.as_view(template_name='topmenu.html')),
    url(r'^accounts/login/$',django.contrib.auth.views.login,{'template_name':'accounts/login.html'},name='login'),
    url(r'^accounts/logout/$',django.contrib.auth.views.logout,{'next_page':'/'}),
    #urls for guests
    url(r'^squidguard/whitesites/$',squidguard.views.WhiteSites.as_view()),
    #squid
    url(r'^squid/$',squid.views.Squid.as_view()),
    url(r'^squid/(?P<model>\w+)/(?P<acl>\w+)/$',squid.views.SquidDetail.as_view()),
    #squidGuard
    url(r'^squidguard/$',squidguard.views.SquidGuard.as_view()),
    url(r'^squidguard/(\w+/){1,5}$',squidguard.views.SquidGuardDetail.as_view()),
    #licenses
    url(r'^licenses/$',licenses.views.Nothing.as_view()),
    url(r'^licenses/create/(?P<model>\w+)/$',licenses.views.Create.as_view()),
    url(r'^licenses/list/(?P<model>\w+)/(?P<pk>\w+)/$',licenses.views.List.as_view()),
    url(r'^licenses/detail/(?P<model>\License)/(?P<pk>\w+)/$',licenses.views.DetailOfLicense.as_view()),
    url(r'^licenses/detail/(?P<model>\Owner)/(?P<pk>\w+)/$',licenses.views.DetailOfOwner.as_view()),
    url(r'^licenses/report/(?P<model>License)/(?P<pk>\w+)/$',licenses.views.ReportOfLicense.as_view()),
    url(r'^licenses/import/$',licenses.views.Import.as_view()),
    #tasker
    url(r'^tasker/$',tasker.views.SimpleView.as_view()),
    url(r'^tasker/listof/(?P<model>TaskG)/(?P<pk>\w+)/$',tasker.views.ListOfTask.as_view()),
    url(r'^tasker/detailof/(?P<model>\w+)/(?P<pk>\w+)/$',tasker.views.DetailOfTask.as_view()),
    url(r'^tasker/edit/(?P<model>\w+)/(?P<pk>\w+)/$',tasker.views.EditTask.as_view()),
    url(r'^tasker/create/(?P<model>\w+)/$',tasker.views.Create.as_view()),
    url(r'^tasker/create/(?P<model>\w+)/(?P<pk>\w+)/$',tasker.views.CreateTask.as_view()),
    #certs
    url(r'^certs/$',certs.views.SimpleView.as_view()),
    url(r'^certs/list/$',certs.views.List.as_view()),
    url(r'^certs/create/(?P<model>\w+)/$',certs.views.Create.as_view()),
    url(r'^certs/detail/(?P<pk>\w+)/$',certs.views.Detail.as_view()),
    url(r'^certs/edit/(?P<pk>\w+)/$',certs.views.Edit.as_view()),
    #mail
    url(r'^mail/list/$',mail.views.List.as_view()),
    url(r'^mail/list/(?P<model>\w+)/(?P<pk>\w+)/$',mail.views.List.as_view()),
    url(r'^mail/create/(?P<model>\w+)/$',mail.views.Create.as_view()),
    url(r'^mail/update/(?P<model>\w+)/(?P<pk>\w+)/$',mail.views.Update.as_view()),
    #hashez
    url(r'^hashez/$',hashez.views.Simple.as_view()),
    url(r'^hashez/events/client/(?P<pk>\w+)/$',hashez.views.EventList.as_view()),
    url(r'^hashez/detail/client/(?P<pk>\w+)/$',hashez.views.ClientDetail.as_view()),
    url(r'^hashez/fileSet/(?P<pk>\w+)/$',hashez.views.FileSet.as_view()),
    url(r'^hashez/badFiles/(?P<pk>\w+)/$',hashez.views.BadFiles.as_view()),
    url(r'^hashez/report/$',hashez.views.Report.as_view()),
]

tasker/models.py
# -*- coding: utf8 -*-

from django.contrib.auth.models import User as Person
from django.db import models
import datetime
import actions,repeat

class TaskG(models.Model):
  name=models.CharField(max_length=20,unique=True)
  description=models.CharField(max_length=100,blank=True)
  email=models.CharField(max_length=200,blank=True)
  member='Task'

  def __unicode__(self):
    return self.name

class Task(models.Model):
  choices=(('1',u'Новое'),
           ('2',u'Нихера непонятно'),
           ('3',u'В работе'),
           ('4','4!'),
           ('5','5!'),
           ('6','6!'),
           ('7','7!'),
           ('8','8!'),
           ('9',u'Отменено'),
           ('10',u'Завершено'),
          )
  notactive=(u'Завершено',
             u'Отменено',
            )
  name=models.CharField(max_length=20)
  description=models.CharField(max_length=100,blank=True)
  text=models.TextField(blank=True)
  addtime=models.DateField(auto_now_add=True)
  starttime=models.DateField(blank=True,null=True)
  #deadtime=models.DateField(blank=True,null=True)
  deadtime=models.DateField(default=datetime.datetime.max)
  repeat=models.IntegerField(choices=repeat.repeat.as_list(),blank=True,null=True)
  nday=models.IntegerField(blank=True,null=True)
  action=models.IntegerField(choices=actions.actions.as_list(),blank=True,null=True)
  email=models.CharField(max_length=200,blank=True)
  private=models.BooleanField(default=False)
  owner=models.ForeignKey(Person,related_name='task_person_owner')
  performer=models.ForeignKey(Person,related_name='task_person_performer')
  group=models.ForeignKey(TaskG)
  state=models.CharField(max_length=10,choices=choices)

  class Meta():
    ordering=['-addtime']

  def __unicode__(self):
    return self.name

class Event(models.Model):
  task=models.ForeignKey(Task)
  lasttime=models.DateField(auto_now_add=True)

class Comment(models.Model):
  owner=models.ForeignKey(Person)
  comment=models.TextField()
  addtime=models.DateTimeField(auto_now_add=True)
  task=models.ForeignKey(Task)

  class Meta():
    ordering=['-addtime']

  def __unicode__(self):
    return self.comment

tasker/forms.py
import models
import django.forms
from django.forms.extras.widgets import SelectDateWidget

class TaskG(django.forms.ModelForm):
  class Meta():
    model=models.TaskG
    fields='__all__'

class Task(django.forms.ModelForm):
  starttime=django.forms.DateField(widget=SelectDateWidget(),required=False)
  deadtime=django.forms.DateField(widget=SelectDateWidget(),required=False)
  class Meta():
    model=models.Task
    exclude=('addtime','owner','group')

class Comment(django.forms.ModelForm):
  class Meta():
    model=models.Comment
    exclude=('addtime','owner','task')

tasker/views.py
# -*- coding:utf8 -*-

from django.shortcuts import get_object_or_404,redirect
from django.views.generic import TemplateView,View,DetailView,ListView
from django.views.generic.edit import CreateView,UpdateView,FormMixin
from django.db.models import Q
from gibloc.mixins import LoginRequiredMixin
import models,forms

class SimpleView(TemplateView):
  template_name='tasker/simpleview.html'
  pass

  def get_context_data(self,**kwargs):
    kwargs['lmenu']=models.TaskG.objects.all()
    return super(SimpleView,self).get_context_data(**kwargs)

class LMenu(View):
  def get_context_data(self,**kwargs):
    kwargs['lmenu']=models.TaskG.objects.all()
    return super(LMenu,self).get_context_data(**kwargs)

class ListOf(LoginRequiredMixin,LMenu,ListView):
  def get_queryset(self,*argv,**kwargs):
    group=getattr(models,self.kwargs['model'])
    model=getattr(models,group.member)
    q=model.objects.filter(Q(group=group.objects.get(id=self.kwargs['pk'])),
                           Q(performer=self.request.user)|
                           Q(owner=self.request.user)|
                           Q(private=False)).order_by(self.order_by)
    if self.reverse:
      return q.reverse()
    else:
      return q

  def post(self,request,*argv,**kwargs):
    if request.POST.get('submit')=='Delete':
      for i in request.POST.getlist('select'):
        getattr(models,getattr(models,self.kwargs['model']).member).objects.get(pk=i).delete()
    #return super(ListOf,self).get(request,*argv,**kwargs)
    return self.get(request,*argv,**kwargs)

  def get(self,request,*argv,**kwargs):
    self.order_by=request.GET.get('order_by','addtime')
    self.reverse=False if request.GET.get('reverse','True')=='False' else True
    return super(ListOf,self).get(request,*argv,**kwargs)

  def get_context_data(self,**kwargs):
    kwargs['reverse']=not self.reverse
    return super(ListOf,self).get_context_data(**kwargs)

class ListOfTask(ListOf):
  template_name='tasker/listoftask.html'

  def get_context_data(self,**kwargs):
    kwargs['TaskG']=self.kwargs['pk']
    return super(ListOfTask,self).get_context_data(**kwargs)

class DetailOf(LoginRequiredMixin,LMenu,DetailView):
  def get_queryset(self):
    return getattr(models,self.kwargs['model']).objects.all()

class DetailOfTask(LoginRequiredMixin,LMenu,CreateView):
  template_name='tasker/detailoftask.html'
  form_class=forms.Comment

  def get_context_data(self,**kwargs):
    kwargs['object']=models.Task.objects.get(pk=self.kwargs['pk'])
    kwargs['comments']=models.Comment.objects.filter(task=kwargs['object'])
    return super(DetailOfTask,self).get_context_data(**kwargs)

  def get_success_url(self):
    return self.request.path

  def post(self,request,*argv,**kwargs):
    action=request.POST.get('submit')
    if action=='add':
      return super(DetailOfTask,self).post(request,*argv,**kwargs)
    elif  action=='delete':
      for i in request.POST.getlist('select'):
        models.Comment.objects.get(pk=i).delete()
    return redirect(self.get_success_url())

  def form_valid(self,form):
    form.instance.owner=self.request.user
    form.instance.task=models.Task.objects.get(pk=self.kwargs['pk'])
    return super(DetailOfTask,self).form_valid(form)

class Create(LoginRequiredMixin,LMenu,CreateView):
  template_name='tasker/create.html'
  def dispatch(self,request,*args,**kwargs):
    self.form_class=getattr(forms,kwargs.get('model'))
    self.success_url=request.path
    return super(Create,self).dispatch(request,*args,**kwargs)

class CreateTask(LoginRequiredMixin,LMenu,CreateView):
  template_name='tasker/createtask.html'
  form_class=forms.Task

  def get_success_url(self):
    return '/tasker/detailof/Task/%s'% self.object.pk

  def get_queryset(self):
    group=getattr(models,self.kwargs['model'])
    return getattr(models,group.member).objects.all()

  def form_valid(self,form):
    form.instance.owner=self.request.user
    form.instance.group=getattr(models,self.kwargs['model']).objects.get(pk=self.kwargs['pk'])
    return super(CreateTask,self).form_valid(form)

class Edit(LoginRequiredMixin,LMenu,UpdateView):

  def get_success_url(self):
    return '/tasker/detailof/Task/%s' % self.object.pk

  def get_object(self):
    model=getattr(models,self.kwargs['model'])
    self.form_class=getattr(forms,self.kwargs['model'])
    return get_object_or_404(model,pk=self.kwargs['pk'])

class EditTask(Edit):
  template_name='tasker/edittask.html'

templates/tasker/create.html
{% extends 'tasker/leftmenu.html' %}
{% block content %}
<form method="post"> {% csrf_token %}
<table>
{{form.as_table}}
</table>
<input type="submit" name="submit" value="Create"/>
<input type="submit" name="submit" value="Cancel"/>
</form>
{% endblock %}

templates/tasker/createtask.html
{% extends 'tasker/leftmenu.html' %}
{% block content %}
<form method="post"> {% csrf_token %}
<table>
{{form.as_table}}
</table>
<input type="submit" name="submit" value="Create"/>
<input type="submit" name="submit" value="Cancel"/>
</form>
{% endblock %}

templates/tasker/detailof.html
{% extends 'tasker/leftmenu.html '%}
{% block content%}
<table>
<tr><th>name:</th>
<td>{{object.name}}</td></tr>
<tr><th>description:</th>
<td>{{object.description}}</td></tr>
<tr><th>text:</th>
<td>{{object.text}}</td></tr>
<tr><th>addtime:</th>
<td>{{object.addtime}}</td></tr>
<tr><th>deadtime:</th>
<td>{{object.deadtime}}</td></tr>
<tr><th>repeat:</th>
<td>{{object.repeat}}</td></tr>
<tr><th>nday:</th>
<td>{{object.nday}}</td></tr>
<tr><th>action:</th>
<td>{{object.action}}</td></tr>
<tr><th>private:</th>
<td>{{object.private}}</td></tr>
<tr><th>owner:</th>
<td>{{object.owner}}</td></tr>
<tr><th>performer:</th>
<td>{{object.performer}}</td></tr>
<tr><th>group:</th>
<td>{{object.group}}</td></tr>
</table>
{% endblock %}

templates/tasker/detailoftask.html
{% extends 'tasker/leftmenu.html' %}
{% block content%}
<form method="post" action=""> {% csrf_token %}
<table>
<tr><th>name:</th><td>{{object.name}} <a href="/tasker/edit/Task/{{object.id}}">edit</a></td><th>description:</th><td>{{object.description}}</td><td rowspan="8"><table>{{form.as_table}}</table><input type="submit" name="submit" value="add"></tr>
<tr><th colspan="4">text:</th></tr>
<tr><td colspan="4">{% autoescape off %}{{object.text}}{% endautoescape %}</td></tr>
<tr><th>addtime:</th><td>{{object.addtime}}</td><th>deadtime:</th><td>{{object.deadtime}}</td></tr>
<tr><th>repeat:</th><td>{{object.get_repeat_display}}</td><th>nday:</th><td>{{object.nday}}</td></tr>
<tr><th>action:</th><td>{{object.get_action_display}}</td><th>private:</th><td>{{object.private}}</td></tr>
<tr><th>owner:</th><td>{{object.owner}}</td><th>performer:</th><td>{{object.performer}}</td></tr>
<tr><th>group:</th><td>{{object.group}}</td><th>state:</th><td>{{object.get_state_display}}</td></tr>
</table>
<table>
<tr><td colspan="2">comments:</td></tr>
{% for comment in comments %}
  <tr><td width="20" rowspan="3"><input type="checkbox" name="select" value="{{comment.pk}}"></td><th>{{comment.owner}}</th><tr>
  <tr><td>{{comment.comment|linebreaks}}</td><tr>
{% endfor %}
</table>
<input type="submit" name="submit" value="delete">
</form>
{% endblock %}

templates/tasker/edittask.html
{% extends "tasker/leftmenu.html" %}
{% block content %}
  <form method="post" action=""> {% csrf_token %}
  <table>
  {{form.as_table}}
  </table>
  <input type="submit" name="submit" value="Save">
  </form>
{% endblock %}

templates/tasker/leftmenu.html
{% extends "topmenu.html" %}
{% block leftmenu %}
<ul>TaskG
{% for i in lmenu %}
  <li><a href="/tasker/listof/TaskG/{{i.id}}">{{i.name}}</a></li>
{% endfor %}
<a class="small" href="/tasker/create/TaskG">+ Новый</a>
</ul>
{% endblock %}

templates/tasker/listof.html
{% extends 'tasker/leftmenu.html' %}
{%load getattribute %}
{% block content %}
  <form method="post" action=""> {% csrf_token %}
  <table>
  {{form.as_table}}
  </table>
  <input type="submit" name="action" value="add">
  <br/>
  <table>
  <tr><th></th>
  {% for field in fields.values %}
    <th>{{field}}</th>
  {% endfor %}
  </tr>
  {% for member in members%}
    <tr><td><input type="checkbox" name="select" value="{{member.id}}"/></td>
    {% for field in fields.keys %}
      <td><a href="/tasker/detailof/{{member}}">{{member|getattribute:field}}</a></td>
    {% endfor %}
    </tr>
  {% endfor %}
  </table>
  </form>
{% endblock %}

templates/tasker/listoftask.html
{% extends 'tasker/leftmenu.html' %}
{%load getattribute%}
{% block content %}
  <form method="post"> {% csrf_token %}
  <a href="/tasker/create/TaskG/{{TaskG}}">Create new</a>
  <br/>
  <table>
  <tr>
    <th></th>
    <th><a href="?order_by=name&reverse={{reverse}}">name</a></th>
    <th>description</th>
    <th><a href="?order_by=addtime&reverse={{reverse}}">addtime</a></th>
    <th><a href="?order_by=deadtime&reverse={{reverse}}">deadtime</a></th>
    <th><a href="?order_by=owner&reverse={{reverse}}">owner</a></th>
    <th><a href="?order_by=performer&reverse={{reverse}}">performer</a></th>
    <th><a href="?order_by=state&reverse={{reverse}}">state</a></th>
  </tr>
  {% for object in object_list%}
    <tr>
      <td><input type="checkbox" name="select" value="{{object.id}}"/></td>
      <td><a href="/tasker/detailof/Task/{{object.id}}">{{object.name}}</a></td>
      <td>{{object.description}}</td>
      <td>{{object.addtime}}</td>
      <td>{{object.deadtime}}</td>
      <td>{{object.owner}}</td>
      <td>{{object.performer}}</td>
      <td>{{object.get_state_display}}</td>
    </tr>
  {% endfor %}
  </table>
  <input type="submit" name="submit" value="Delete">
  </form>
{% endblock %}

templates/tasker/simpleview.html
{% extends "tasker/leftmenu.html" %}
{% block content %}
  just content !!!
{% endblock %}

templates/tasker/update.html
{% extends "tasker/leftmenu.html" %}
{% block content %}
  <form method="post" action=""> {% csrf_token %}
  <table>
  {{form.as_table}}
  </table>
  <input type="submit" name="submit" value="Update">
  </form>
{% endblock %}