gibloc/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import *
from django.contrib.auth.views import login
import django
import squid.views
import squidguard.views
import tasker.views
import licenses.views
import certs.views
import mail.views
import hashez.views

admin.autodiscover()

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', 'gibloc.views.home', name='home'),
    # url(r'^gibloc/', include('gibloc.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$',TemplateView.as_view(template_name='topmenu.html')),
    url(r'^accounts/login/$',django.contrib.auth.views.login,{'template_name':'accounts/login.html'},name='login'),
    url(r'^accounts/logout/$',django.contrib.auth.views.logout,{'next_page':'/'}),
    #urls for guests
    url(r'^squidguard/whitesites/$',squidguard.views.WhiteSites.as_view()),
    #squid
    url(r'^squid/$',squid.views.Squid.as_view()),
    url(r'^squid/(?P<model>\w+)/(?P<acl>\w+)/$',squid.views.SquidDetail.as_view()),
    #squidGuard
    url(r'^squidguard/$',squidguard.views.SquidGuard.as_view()),
    url(r'^squidguard/(\w+/){1,5}$',squidguard.views.SquidGuardDetail.as_view()),
    #licenses
    url(r'^licenses/$',licenses.views.Nothing.as_view()),
    url(r'^licenses/create/(?P<model>\w+)/$',licenses.views.Create.as_view()),
    url(r'^licenses/list/(?P<model>\w+)/(?P<pk>\w+)/$',licenses.views.List.as_view()),
    url(r'^licenses/detail/(?P<model>\License)/(?P<pk>\w+)/$',licenses.views.DetailOfLicense.as_view()),
    url(r'^licenses/detail/(?P<model>\Owner)/(?P<pk>\w+)/$',licenses.views.DetailOfOwner.as_view()),
    url(r'^licenses/report/(?P<model>License)/(?P<pk>\w+)/$',licenses.views.ReportOfLicense.as_view()),
    url(r'^licenses/import/$',licenses.views.Import.as_view()),
    #tasker
    url(r'^tasker/$',tasker.views.SimpleView.as_view()),
    url(r'^tasker/listof/(?P<model>TaskG)/(?P<pk>\w+)/$',tasker.views.ListOfTask.as_view()),
    url(r'^tasker/detailof/(?P<model>\w+)/(?P<pk>\w+)/$',tasker.views.DetailOfTask.as_view()),
    url(r'^tasker/edit/(?P<model>\w+)/(?P<pk>\w+)/$',tasker.views.EditTask.as_view()),
    url(r'^tasker/create/(?P<model>\w+)/$',tasker.views.Create.as_view()),
    url(r'^tasker/create/(?P<model>\w+)/(?P<pk>\w+)/$',tasker.views.CreateTask.as_view()),
    #certs
    url(r'^certs/$',certs.views.SimpleView.as_view()),
    url(r'^certs/list/$',certs.views.List.as_view()),
    url(r'^certs/create/(?P<model>\w+)/$',certs.views.Create.as_view()),
    url(r'^certs/detail/(?P<pk>\w+)/$',certs.views.Detail.as_view()),
    url(r'^certs/edit/(?P<pk>\w+)/$',certs.views.Edit.as_view()),
    #mail
    url(r'^mail/list/$',mail.views.List.as_view()),
    url(r'^mail/list/(?P<model>\w+)/(?P<pk>\w+)/$',mail.views.List.as_view()),
    url(r'^mail/create/(?P<model>\w+)/$',mail.views.Create.as_view()),
    url(r'^mail/update/(?P<model>\w+)/(?P<pk>\w+)/$',mail.views.Update.as_view()),
    #hashez
    url(r'^hashez/$',hashez.views.Simple.as_view()),
    url(r'^hashez/events/client/(?P<pk>\w+)/$',hashez.views.EventList.as_view()),
    url(r'^hashez/detail/client/(?P<pk>\w+)/$',hashez.views.ClientDetail.as_view()),
    url(r'^hashez/fileSet/(?P<pk>\w+)/$',hashez.views.FileSet.as_view()),
    url(r'^hashez/badFiles/(?P<pk>\w+)/$',hashez.views.BadFiles.as_view()),
    url(r'^hashez/report/$',hashez.views.Report.as_view()),
]

hashez/models.py
# -*- coding: utf8 -*-

from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User as Person

states=(('OK','OK'),
        ('UPDATED','UPDATED'),
        ('FILESYSTEMERROR','FILESYSTEMERROR'),
        ('CRYPTOERROR','CRYPTOERROR'),
       )

class Client(models.Model):

  def __unicode__(self):
    return self.client

  client=models.CharField(max_length=128,unique=True)
  descr=models.TextField(blank=True)
  registred=models.DateTimeField(auto_now_add=True)

class FileSet(models.Model):

  def __unicode__(self):
    return u"{0}".format(self.id)

  registred=models.DateTimeField(auto_now_add=True)
  client=models.ForeignKey(Client)

class File(models.Model):

  def __unicode__(self):
    return self.path
    
  path=models.CharField(max_length=255)
  checksum=models.BinaryField(null=True)
  state=models.CharField(max_length=32,choices=states)
  updated=models.DateTimeField(auto_now_add=False)
  fileSet=models.ForeignKey(FileSet)

  class Meta():
    unique_together=('path','fileSet')

class Event(models.Model):

  types=((u'CHECK','Контроль'),
         ('UPDATE','Пересчёт'),
         ('NEWCLIENT','Новый клиент'),
         ('NEWFILESET','Новый набор файлов'),
        )

  results=(('PASS','Успешно'),
           ('FAIL','Неудачно')
          )

  def __unicode__(self):
    return unicode(self.eventType)

  eventType=models.CharField(max_length=32,choices=types)
  result=models.CharField(max_length=32,choices=results,blank=True,null=True)
  registred=models.DateTimeField(auto_now_add=True)
  client=models.ForeignKey(Client,null=True,blank=True)
  fileSet=models.ForeignKey(FileSet,null=True,blank=True)

class BadFiles(models.Model):

  def __unicode__(self):
    return self.path

  path=models.CharField(max_length=512)
  checksum=models.BinaryField(null=True)
  state=models.CharField(max_length=32,choices=states)
  event=models.ForeignKey(Event,null=True)

class Comment(models.Model):

  defaultTitle="""
                 
               """

  def __unicode__(self):
    return 0

  docNo=models.IntegerField()
  registred=models.DateTimeField(auto_now_add=True)
  title=models.TextField()
  reason=models.TextField()
  badFiles=models.ForeignKey(BadFiles,null=True)
  action=models.TextField()
  event=models.ForeignKey(Event,null=True)
  person=models.ForeignKey(Person,related_name='hashez_comment_person')

hashez/forms.py
# -*- coding: utf8 -*-

from django import forms
import gibloc.settings

class ReportQueryForm(forms.Form):
  fromDate=forms.DateField(input_formats=gibloc.settings.DATE_INPUT_FORMATS,label=u'Начало')
  toDate=forms.DateField(input_formats=gibloc.settings.DATE_INPUT_FORMATS,label=u'Конец')

hashez/views.py
# -*- coding: utf8 -*-

from django.shortcuts import render
from django.views.generic import ListView,TemplateView,DetailView
from gibloc.mixins import LoginRequiredMixin
import datetime
import models,forms,gibloc

class Simple(LoginRequiredMixin,TemplateView):
  template_name="hashez/simple.html"

class Events(LoginRequiredMixin):
  sqlQuery=""" SELECT E.id,
                      E.eventType,
                      E.result,
                      E.registred,
                      E.fileSet_id,
                      (
                        SELECT count(*)
                        FROM hashez_file F
                        WHERE F.fileSet_id=E.fileSet_id
                      ) as files_count,
                      (
                        SELECT count(*)
                        FROM hashez_badfiles B
                        WHERE B.event_id=E.id
                      ) as badFiles_event_id
               FROM hashez_event E
               WHERE E.client_id={0} {1}
               ORDER BY E.id {2}
           """
  dateFilter="AND (CAST(E.registred AS DATE) BETWEEN '{0}' AND '{1}')"

class EventList(ListView,Events):
  template_name='hashez/events.html'
  form=forms.ReportQueryForm
  err={}

  def dispatch(self,request,*args,**kwargs):
    self.clientId=kwargs.get('pk')
    return super(EventList,self).dispatch(request,*args,**kwargs)

  def get(self,request,*args,**kwargs):
    self.sort=request.GET.get('sort');
    try:
      self.fromDate=datetime.datetime.strptime(request.GET.get('fromDate'),'%d/%m/%Y').date() if request.GET.get('fromDate') else ''
      self.toDate=datetime.datetime.strptime(request.GET.get('toDate'),'%d/%m/%Y').date() if request.GET.get('toDate') else ''
      print self.fromDate
      print self.toDate
    except ValueError,e:
      self.err['toDate']=('Неверный формат даты')
      raise ValueError(e)
    return super(EventList,self).get(request,*args,**kwargs)
  
  def get_queryset(self):
    if(self.fromDate and self.toDate):
      self.dateFilter=self.dateFilter.format(self.fromDate,self.toDate)
    else:
      self.dateFilter=''
    sqlQuery=self.sqlQuery.format(self.clientId,
                                  self.dateFilter,
                                  "DESC" if self.sort=="DESC" else "ASC");
    qset=models.Event.objects.raw(sqlQuery)
    return qset

  def get_context_data(self,**kwargs):
    kwargs['form']=self.form
    kwargs['fromDate']=str(self.fromDate)
    kwargs['toDate']=str(self.toDate)
    kwargs['clientId']=self.clientId
    return super(EventList,self).get_context_data(**kwargs)

class ClientDetail(LoginRequiredMixin,DetailView):
  template_name='hashez/clientDetail.html'
  model=models.Client
  clientId=0

  def dispatch(self,request,*args,**kwargs):
    self.clientId=kwargs.get('pk')
    return super(ClientDetail,self).dispatch(request,*args,**kwargs)

  def get_context_data(self,**kwargs):
    fileSets=models.FileSet.objects.filter(client_id=self.clientId)
    fileSet=fileSets.latest('pk')
    events=models.Event.objects.filter(client_id=self.clientId)
    lastEvent=events.latest('pk')
    files=models.File.objects.filter(fileSet=fileSet)
    kwargs['fileSets']=fileSets
    kwargs['lastEvent']=lastEvent
    kwargs['files']=files
    return super(ClientDetail,self).get_context_data(**kwargs)

class FileSet(LoginRequiredMixin,ListView):
  template_name="hashez/fileSet.html"

  def get(self,request,*args,**kwargs):
    action=request.GET.get('action')
    if(action=="report"):
      self.template_name='hashez/fileSetReport.html'
    return super(FileSet,self).get(request,*args,**kwargs)

  def dispatch(self,request,*args,**kwargs):
    self.fileSetId=kwargs.get('pk');
    return super(FileSet,self).dispatch(request,*args,**kwargs)

  def get_queryset(self):
    return models.File.objects.filter(fileSet_id=self.fileSetId)

  def get_context_data(self,**kwargs):
    fileSet=models.FileSet.objects.get(pk=self.fileSetId)
    clientId=fileSet.client_id
    kwargs['fileSet']=fileSet
    kwargs['client']=models.Client.objects.get(pk=clientId)
    return super(FileSet,self).get_context_data(**kwargs)

class BadFiles(LoginRequiredMixin,ListView):
  template_name="hashez/badFiles.html"
  model=models.BadFiles

  def dispatch(self,request,*args,**kwargs):
    self.eventId=kwargs.get("pk")
    return super(BadFiles,self).dispatch(request,*args,**kwargs)

  def get_queryset(self):
    return self.model.objects.filter(event_id=self.eventId)

class Report(ListView,Events):
  template_name="hashez/report.html"

  def get(self,request,*args,**kwargs):
    self.clientId=request.GET.get("clientId")
    self.fromDate=request.GET.get("fromDate")
    self.toDate=request.GET.get("toDate")
    return super(Report,self).get(request,*args,**kwargs)

  def get_queryset(self):
    self.dateFilter=self.dateFilter.format(self.fromDate,self.toDate)
    sqlQuery=self.sqlQuery.format(self.clientId,
                                  self.dateFilter,
                                  "ASC",
                                 )
    qset=models.Event.objects.raw(sqlQuery)
    return qset

  def get_context_data(self,**kwargs):
    kwargs['clientId']=self.clientId
    kwargs['fromDate']=self.fromDate
    kwargs['toDate']=self.toDate
    kwargs['client']=models.Client.objects.get(pk=self.clientId)
    return super(Report,self).get_context_data(**kwargs)

templates/hashez/ClientDetail.html
{% extends 'hashez/leftmenu.html' %}
{% block content %}

<table>
<tr>
<td>Имя клиента</td>
<td>{{object.client}}</td>
<tr>
</tr>
<td>Описание</td>
<td>{{object.descr}}</td>
<tr>
</tr>
<td>Зарегистрирован</td>
<td>{{object.registred}}</td>
</tr>
<tr>
<td>Время последнего события</td>
<td><a href="/hashez/events/client/{{object.id}}/?sort=DESC">{{lastEvent.registred}}</a></td>
</tr>
</table>

<table>
<tr>
<td>Файл</td><td>Результат проверки</td><td>Время проверки</td>
</tr>
{% for item in files %}
<tr class={% cycle "bg_a" "bg_b" %}>
<td>{{item}}</td><td>{{item.state}}</td><td>{{item.updated}}</td>
</tr>
{% endfor %}
</table>

{% endblock %}

templates/hashez/FileSetReport.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01// EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}"/>
</head>
<body>
{% block content %}
<table align="center">
<tr><td>АРМ:</td><td>{{client.client}}</td></tr>
<tr><td>Описание:</td><td>{{client.descr}}</td></tr>
<tr><td colspan=2>Список файлов подлежащих проверке(создано {{fileSet.registred}}):</td></tr>
</table>
<br/>
<table>
<tr>
<td>Полный путь</td>
<!--
<td>Состояние</td>
<td>Обновлен</td>
-->
</tr>
{% for object in object_list %}
<tr>
<td>{{object.path}}</td>
<!--
<td>{{object.state}}</td>
<td>{{object.updated}}</td>
-->
</tr>
{% endfor %}
</table>
{% endblock %}

templates/hashez/badFiles.html
{% extends 'hashez/leftmenu.html' %}
{% block content %}
<table>
<tr>
<td>Полный путь</td>
<td>Состояние</td>
<td>Событие</td>
</tr>
{% for object in object_list %}
<tr>
<td>{{object.path}}</td>
<td>{{object.state}}</td>
<td>{{object.event_id}}</td>
</tr>
{% endfor %}
</table>
{% endblock %}

templates/hashez/events.html
{% extends 'hashez/leftmenu.html' %}
{% block content %}
<form method="GET" action="">
<table>
{{form.as_table}}
</table>
<input type="hidden" name="sort" value="DESC"/>
<input type="submit" name="action" value="OK" text="!!!"/>
<a href="/hashez/report/?clientId={{clientId}}&fromDate={{fromDate}}&toDate={{toDate}}" target="_blank">Отчёт</a>
</form>
<table class="center">
<tr>
  <td>Тип события</td>
  <td>Результат выполнения</td>
  <td>Время события</td>
  <td>Ошибки проверки</td>
  <td>Всего файлов</td>
  <td>Сопроводительный документ</td>
</tr>
{% for event in object_list %}
<tr class={% cycle "bg_a" "bg_b"%}>
  <td>{{event.get_eventType_display}}</td>
  <td>{{event.get_result_display}}</td>
  <td>{{event.registred}}</td>
  <td>
    {% if event.badFiles_event_id %}
      <a href="/hashez/badFiles/{{event.id}}">{{event.badFiles_event_id}}</a>
    {% else %}
      ---
    {% endif %}
  </td>
  <td>
    {% if event.fileSet_id %}
      <a href="/hashez/fileSet/{{event.fileSet_id}}">{{event.files_count}}</a>
    {% else %}
      ---
    {% endif %}
  </td>
  <td>
    {% if event_badFiles_id %}
      <a href="/hashez/reports/###">###</a>
    {% else %}
      ---
    {% endif %}
  </td>
</tr>
{% endfor %}
</table>
{% endblock %}

templates/hashez/fileSet.html
{% extends 'hashez/leftmenu.html' %}
{% block content %}
<a href="/hashez/fileSet/{{fileSet.id}}/?action=report" targer="_blank">Отчёт</a>
<table>
<tr>
<td>Полный путь</td>
<td>Состояние</td>
<td>Обновлен</td>
</tr>
{% for object in object_list %}
<tr>
<td>{{object.path}}</td>
<td>{{object.state}}</td>
<td>{{object.updated}}</td>
</tr>
{% endfor %}
</table>
{% endblock %}

templates/hashez/leftmenu.html
{% extends 'topmenu.html' %}
{% load hashez_lmenu %}
{% block leftmenu %}
Клиенты
{% navigation %}
{% endblock %}

templates/hashez/navigation.html
{% for client in clients %}
  </br>
  <a href="/hashez/detail/client/{{client.pk}}/">- {{client}}</a>
{% endfor %}

templates/hashez/report.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01// EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}"/>
</head>
<body>
{% block content %}
<table class="center">
<tr>
<td colspan=2><h3>Отчёт о проверке контрольных сумм критичных файлов на клиенте:</h3></td>
</tr>
<tr>
<td>{{client}}</td>
<td>{{client.descr}}</td>
</tr>
<tr>
<td colspan=2><h4>за период:</h4></td>
</tr>
<tr>
<td>c: {{fromDate}}</td>
<td>по: {{toDate}}</td>
</tr>
</table>

<table class="center">
<tr>
  <td>Тип события</td>
  <td>Результат выполнения</td>
  <td>Время события</td>
  <td>Ошибки проверки</td>
  <td>Всего файлов</td>
  <td>Сопроводительный документ</td>
</tr>
{% for event in object_list %}
<tr class={% cycle "bg_a" "bg_b"%}>
  <td>{{event.eventType}}</td>
  <td>{{event.result}}</td>
  <td>{{event.registred}}</td>
  <td>
    {% if event.badFiles_event_id %}
      <a href="/hashez/badFiles/{{event.id}}">>>></a>
    {% else %}
      ---
    {% endif %}
  </td>
  <td>
    {% if event.fileSet_id %}
      <a href="/hashez/fileSet/{{event.fileSet_id}}">{{event.files_count}}</a>
    {% else %}
      ---
    {% endif %}
  </td>
  <td>
    {% if event_badFiles_id %}
      <a href="/hashez/reports/###">###</a>
    {% else %}
      ---
    {% endif %}
  </td>
</tr>
{% endfor %}
</table>

{% endblock %}
</body>

templates/hashez/simple.html
{% extends "hashez/leftmenu.html" %}
{% block content %}
jaust content !!!
{% endblock %}